### ISSUE TITLE
The results returned are limited to 100 rows.

### ISSUE THREAD

**Issue by iguissouma** [veeraRaghavSanthosh/sharepointConnector#2]
When listing items, the results returned are limited to 100 rows, $limit does not work for me in SharePoint 2013

I changed $limit to $top then the results become more than 100.

Can you verify this point.
Thanks.

**Comment by veeraRaghavSanthosh** [comment]
Thanks for the information. This is corrected in the new release.

Thanks
Veer

**Comment by iguissouma** [comment]
thanks
