### ISSUE TITLE
sharepoint.lists.read('aadc2cfd-c44a-4ea1-a929-64832794f011', ...)  --> Status Code: 404

### ISSUE THREAD

**Issue by nagybar** [veeraRaghavSanthosh/sharepointConnector#3]
Cant call the sharepoint.lists.read() with an Id.

The problem is probably here:
Step 1 (lists.js line 57):    _Items: async.apply(listItems.list, guid)_
Step 2 (listItems.js line 10):   _var host = client.BASE_LIST_URL + "/getByTitle('" + listId + "')" + "/Items";_

The code call the SharePoint with "**getByTitle**" but listId contains an **Id** instead of a **Title**.

**Comment by veeraRaghavSanthosh** [comment]
Hi,
please pass title instead of list id it will work. right now, GUID's or list id's are not supported. 

Thanks
Veer

**Comment by veeraRaghavSanthosh** [comment]
please try this 

sharepoint.lists.read('Title', ...) -->200
