### ISSUE TITLE
value: 'The expression "web/lists(guid\'abcdef00eb684e0a6fa5e92fbd3333ef\')/Fields" is not valid.'

### ISSUE THREAD

**Issue by tec1106** [veeraRaghavSanthosh/sharepointConnector#8]
It seems the backslashes before the single quotes makes the expression invalid. I might be doing something wrong, but I followed the instruction closely.

```
sharepoint.lists.read('abcdef00eb684e0a6fa5e92fbd3333ef', function(err, listReadResults){
    if(err) {
        console.log(err)
     }
```

This is the full error:

```
{ message:
   { lang: 'en-US',
     value: 'The expression "web/lists(guid\'abcdef00eb684e0a6fa5e92fbd3333ef\')/Fields" is not valid.' },
  body:
   { error:
      { code: '-1, Microsoft.SharePoint.Client.InvalidClientQueryException',
        message: [Object] } },
  statusCode: 400 }
```

Edit: Using the title instead of an ID gives me 'Undefined' as title if the title exist for a list

**Comment by veeraRaghavSanthosh** [comment]
Hi Kim.

Please use SharePoint  list name instead of List GUID (‘abcdef00eb684e0a6fa5e92fbd3333ef’)


sharepoint.lists.read(‘samplelist’, function(err, listReadResults){

    if(err) {

        console.log(err)

     }

Thanks and Regards,
Veer

**Comment by tec1106** [comment]
Hi, Veer. 

Thank you for your reply. 

I tried this:

```
sharepoint.lists.read('Documents', function(err, listReadResults){
    		if(err) {
    			console.log(err)
    		}
```

But got the same error:

`value: 'The expression "web/lists(guid\'Documents\')" is not valid.' },`

**Comment by veeraRaghavSanthosh** [comment]
Kindly please try this approach.

sharepoint.lists.read({title : 'list name' }, function(err, listReadResult){
  // listReadResult will be an object { Id : 'list name', Title : 'some list name', ... }
});

Thanks and Regards,
Veer

**Comment by tec1106** [comment]
I tried this: 

```
sharepoint.lists.read({title : 'Documents' }, function(err, listReadResults){
    		if(err) {
    			console.log(err)
    		}
```

Even though I know there is a list titled 'Documents' it gave me this;

`value: 'List \'undefined\' does not exist at site' },`
